# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repoName: "fm-api"
  acr: "DR-DevToolsLyon"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(repoName)
        dockerfile: '**/Dockerfile'
        containerRegistry: $(acr)
        tags: |
          $(tag)

- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(repoName)
        containerRegistry: $(acr)
        tags: |
          $(tag)
